### ISSUE TITLE
Did not get a ticket in the login response. 

### ISSUE THREAD

**Issue by samirshaikh** [euri10/gols#1]
I have been successfully using gols (on Linux) for the past couple of wks but since last evening been getting this error
Exception: Did not get a ticket in the login response. Cannot log in. Did you enter the correct username and password?

I have a simple bash scripts which feeds the userid/password which hasn't changed and I verified that the username/password is correct. Below is the debug log of the run.

INFO:gols.cli:Debug level set on
INFO:gols.cli:Uplading stuff
INFO:gols.cli:Login into Garmin connect
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sso.garmin.com:443
DEBUG:urllib3.connectionpool:https://sso.garmin.com:443 "GET /sso/login?openCreateAccount=false&createAccountShown=true&consumeServiceTicket=false&embedWidget=false&service=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&webhost=https%3A%2F%2Fconnect.garmin.com&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&rememberMeShown=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&usernameShown=false&clientId=GarminConnect&id=gauth-widget&source=http%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&initialFocus=true&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&rememberMeChecked=false&locale=en_US&displayNameShown=false&generateExtraServiceTicket=false&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://sso.garmin.com:443 "POST /sso/login?openCreateAccount=false&createAccountShown=true&consumeServiceTicket=false&embedWidget=false&service=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&webhost=https%3A%2F%2Fconnect.garmin.com&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin&rememberMeShown=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&usernameShown=false&clientId=GarminConnect&id=gauth-widget&source=http%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&initialFocus=true&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&rememberMeChecked=false&locale=en_US&displayNameShown=false&generateExtraServiceTicket=false&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fpost-auth%2Flogin HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/samir/.local/bin/gols", line 11, in <module>
    sys.exit(main())
  File "/home/samir/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/samir/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/samir/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/samir/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/samir/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/samir/.local/lib/python2.7/site-packages/gols/cli.py", line 121, in upload
    raise Exception('Did not get a ticket in the login response. Cannot log in. Did you enter the correct username and password?')
Exception: Did not get a ticket in the login response. Cannot log in. Did you enter the correct username and password?

**Comment by euri10** [comment]
yes it seems Garmin changed once again the login process,
you can watch those issues that will likely solve this before me as I'm heading on HOLIDAYS ;) but as soon as it's fixable I'll push it,
https://github.com/moderation/garmin-connect-export/issues/25
https://github.com/pe-st/garmin-connect-export/issues/22

**Comment by samirshaikh** [comment]
Thanks for the quick response. Will keep an eye.

**Comment by samirshaikh** [comment]
New to github, seems like there is fix so wondering what is the next step?

**Comment by euri10** [comment]
Sorry for the time taken, I'm afk on holidays, it seems a PR fixing it has
been sent, you can grab the fork or wait until I incorporate it 😉

Le ven. 3 mai 2019 à 9:08 AM, samirshaikh <notifications@github.com> a
écrit :

**Comment by samirshaikh** [comment]
Thanks. I grabbed the fork and it seems to be working again.
Thanks @SibrenVasse for the fix.

**Comment by euri10** [comment]
thanks @SibrenVasse
